allowBuilds:
  esbuild: true
  sharp: true
  spawn-sync: true
  unrs-resolver: set this to true or false
supportedArchitectures:
  cpu:
    - current
    - x64
  os:
    - current
    - win32
    - linux
